---
- name: Server for Docker
  hosts: docker
  tasks:


    - name: Block Dowload
      block:


       - name: Fers step Directori
         apt_repository:
           repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
           state: present


       - name: Install packeges    
         apt:
           name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
           update_cache: yes
           cache_valid_time: 86400


       - name: Добавление ключав докер
         apt_key:
           url: https://download.docker.com/linux/ubuntu/gpg
           state: present
           keyring: /usr/share/keyrings/docker-archive-keyring.gpg


       - debug:
           msg: "https://download.docker.com/linux/ubuntu/dists/{{ ansible_distribution_release }}/stable"
        
       - name: Настройка репозитория Docker
         apt_repository:
          repo: > 
            deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
            https://download.docker.com/linux/ubuntu/ 
            {{ ansible_distribution_release }} stable
          state: present
          update_cache: yes
          filename: docker



       - name: Install Docker   
         apt:
           name: docker-ce
           update_cache: yes



       - name: Проверка стоит ли докер   
         service:
           name: docker
           state: restarted
           enabled: yes
      become: yes

    - name: Установка Docker-compose
      block:
         - name: Получение последней версии docker-compose
           uri: 
             url: https://api.github.com/repos/docker/compose/releases/latest
             body_format: json
           register: page
         - name: print home_dirs variable
           ansible.builtin.debug:
             var: page.json.tag_name

         - name: Установка
           get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: yes    
    - name: Завершение установки Docker
      block:
         - name: Добавление пользователя в группу Docker
           user:
             name: "{{ ansible_user }}"
             group: docker
             append: yes
         - name: Перезагрузка
           reboot:
      become: yes 